name: CI - Type Check, Build

on:
  pull_request:
    branches: [ main, develop ]  # PR이 main, develop 브랜치에 올라왔을 때 실행

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Node 버전 셋업
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20  # 또는 22 (LTS 버전 사용)

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 타입 체크
      - name: Type Check
        run: npm run type-check

      # 5. 빌드
      - name: Build
        run: npm run build