name: Synchronize to forked repo

on:
  push:
    branches:
      - main # main 브랜치에 push 발생 시 실행

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest # GitHub Actions 가상 환경

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked-repo https://[your-github-name]:${{ secrets.AUTO_ACTIONS }}@github.com/[your-github-name]/[your-repo-name]
          git config user.name [your-github-name]
          git config user.email ${{ secrets.EMAIL }}

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo main

      - name: Clean up
        run: |
          git remote remove forked-repo
