name: Synchronize to forked repo

on:
  push:
    branches:
      - main # main 브랜치에 push 발생 시 실행
      - develop # develop 브랜치에 push 발생 시 실행

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest # GitHub Actions 가상 환경

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0

      - name: Determine target branch
        id: vars
        run: |
          BRANCH=$(basename "${{ github.ref }}")
          echo "TARGET_BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Add remote-url
        run: |
          git remote add forked-repo https://farmsystem-account:${{ secrets.AUTO_ACTIONS }}@github.com/farmsystem-account/HomePage-FE
          git config user.name farmsystem-account
          git config user.email ${{ secrets.EMAIL }}

      # 게임 애들꺼 push 제외
      - name: Exclude Unity WebGL build (deploy-only)
        run: |
          # Remove from index if present, but do not fail if missing
          git rm -r --cached --ignore-unmatch apps/farminglog/public/WebGLBuild || true
          # Create a temporary commit only in the workflow context
          git commit -m "chore(ci): exclude apps/farminglog/public/WebGLBuild from deploy sync" || echo "No changes to commit"

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo ${{ env.TARGET_BRANCH }}

      - name: Clean up
        run: |
          git remote remove forked-repo