name: Synchronize to forked repo

on:
  push:
    branches:
      - main # main 브랜치에 push 발생 시 실행
      - develop # develop 브랜치에 push 발생 시 실행

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest # GitHub Actions 가상 환경

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0

      - name: Add remote-url
        run: |
          git remote add forked-repo https://dewbeeny:${{ secrets.AUTO_ACTIONS }}@github.com/dewbeeny/HomePage-FE
          git config user.name dewbeeny
          git config user.email ${{ secrets.EMAIL }}

      - name: Push main branch to forked-repo
        run: |
          git push -f forked-repo main

      - name: Push develop branch to forked-repo
        run: |
          git checkout develop || git checkout -b develop
          git push -f forked-repo develop

      - name: Clean up
        run: |
          git remote remove forked-repo
