name: Sync Changes to Forked Repo

on:
  push:
    branches:
      - develop
      - main

jobs:
  sync:
    name: Sync with Forked Repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Forked Repo as Remote
        run: |
          git remote add forked https://x-access-token:${{ secrets.AUTO_ACTIONS }}@github.com/dewbeeny/HomePage-FE.git
          git fetch forked

      - name: Push Changes to Forked Repo
        run: |
          git push -f forked develop
