name: Trigger Fork Sync

on:
  push:
    branches:
      - develop
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch event to forked repo
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.AUTO_ACTIONS }}" \
          https://api.github.com/repos/dewbeeny/HomePage-FE/dispatches \
          -d '{"event_type": "sync-fork"}'
